Repository joyent/java-manta, pull requests merged in 2019-05, with the labels that each got.

#514 Updated MantaVersion.java, Remove hardcoded Date Value
  java-manta-client-unshaded/src/main/java/com/joyent/manta/util/MantaVersion.java
Labels: low-priority

#516 Added FAQ Doc Changes, Fixes #482
  FAQ.md
Labels: enhancement, low-priority

#517 Standardize TCPSocketConnectionTimeoutIT
  java-manta-it/src/test/java/com/joyent/manta/http/TCPSocketConnectionTimeoutIT.java
Labels: enhancement, test-bug

#528 Removing the usage of an extra MantaClient.SEPARATOR from the test cases
  java-manta-client-unshaded/src/test/java/com/joyent/manta/http/EncryptedHttpHelperTest.java
  java-manta-it/src/test/java/com/joyent/manta/client/MantaClientDirectoriesIT.java
  java-manta-it/src/test/java/com/joyent/manta/client/MantaClientErrorIT.java
  java-manta-it/src/test/java/com/joyent/manta/client/MantaClientIT.java
  java-manta-it/src/test/java/com/joyent/manta/client/MantaClientMetadataIT.java
  java-manta-it/src/test/java/com/joyent/manta/client/MantaDirectoryListingIteratorIT.java
  java-manta-it/src/test/java/com/joyent/manta/client/jobs/MantaClientJobIT.java
  java-manta-it/src/test/java/com/joyent/manta/client/jobs/MantaJobBuilderIT.java
  java-manta-it/src/test/java/com/joyent/manta/config/IntegrationTestConfigContext.java
  java-manta-it/src/test/java/com/joyent/manta/http/ApacheHttpGetResponseEntityContentContinuatorIT.java
  java-manta-it/src/test/java/com/joyent/manta/http/MantaHttpHeadersIT.java
Labels: enhancement, test-bug

#526 allow signed url integration tests to work with MANTA_TLS_INSECURE
  java-manta-it/src/test/java/com/joyent/manta/client/MantaClientSigningIT.java
Labels: enhancement, test-bug

#532 Fixes #531 by upgrading Maven plugins
  java-manta-benchmark/pom.xml
  java-manta-cli/pom.xml
  pom.xml
Labels: enhancement

#533 Buckets Error Codes and Base Path for Buckets Integration-Tests
  java-manta-client-unshaded/src/main/java/com/joyent/manta/exception/MantaErrorCode.java
  java-manta-client-unshaded/src/test/java/com/joyent/manta/exception/MantaErrorCodeTest.java
  java-manta-it/src/test/java/com/joyent/manta/config/IntegrationTestConfigContext.java
Labels: enhancement, good first issue
