Repository joyent/java-manta, pull requests merged in 2019-04, with the labels that each got.

#501 Fix 470 and Update MantaErrorCode Enum Values
  java-manta-client-unshaded/src/main/java/com/joyent/manta/exception/MantaErrorCode.java
  java-manta-client-unshaded/src/test/java/com/joyent/manta/exception/MantaErrorCodeTest.java
Labels: bug, enhancement, good first issue

#510 Allow completely disabling TLS cert verification for testing
  CHANGELOG.md
  FAQ.md
  USAGE.md
  java-manta-client-unshaded/src/main/java/com/joyent/manta/config/AuthAwareConfigContext.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/config/BaseChainedConfigContext.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/config/ConfigContext.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/config/ConfigContextMBean.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/config/DefaultsConfigContext.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/config/EnvVarConfigContext.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/config/MapConfigContext.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/config/SettableConfigContext.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/http/MantaSSLConnectionSocketFactory.java
  java-manta-client-unshaded/src/test/java/com/joyent/manta/client/AuthAwareConfigContextTest.java
  java-manta-client-unshaded/src/test/java/com/joyent/manta/config/ChainedConfigContextTest.java
  java-manta-client-unshaded/src/test/java/com/joyent/manta/config/SystemSettingsConfigContextTest.java
  java-manta-client-unshaded/src/test/java/com/joyent/manta/config/TestConfigContext.java
Labels: enhancement, good first issue

#512 Missing configs in AuthAwareConfigContext, ConfigContextMBean
  DEVELOPING.md
  java-manta-client-unshaded/src/main/java/com/joyent/manta/config/AuthAwareConfigContext.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/config/ConfigContextMBean.java
  java-manta-client-unshaded/src/test/java/com/joyent/manta/client/AuthAwareConfigContextTest.java
Labels: bug, enhancement
