Repository joyent/java-manta, pull requests merged in 2020-03, with the labels that each got.

#561 Instructions on improving encryption performance for SunPKCS11
  USAGE.md
  pom.xml
Labels: dependencies, documentation, enhancement

#562 MANTA-5083 MANTA JAVA client is taking too long to get file when range start is big.
  java-manta-client-unshaded/src/main/java/com/joyent/manta/client/crypto/AbstractAesCipherDetails.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/client/crypto/AesCtrCipherDetails.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/client/crypto/LocallyIllegalAesCipherDetails.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/client/crypto/MantaEncryptedObjectInputStream.java
  java-manta-client-unshaded/src/main/java/com/joyent/manta/client/crypto/SupportedCipherDetails.java
Labels: enhancement

#563 MANTA-5075 close() function is working as expected
  java-manta-client-unshaded/src/main/java/com/joyent/manta/client/MantaObjectInputStream.java
  java-manta-it/src/test/java/com/joyent/manta/client/MantaClientIT.java
Labels: bug, enhancement, good first issue

#564 Documentation updates for release 3.4.2
  CHANGELOG.md
Labels: documentation
